### ISSUE TITLE
Tian - Fixes

### ISSUE THREAD

**Issue by soggybag** [soggybag/shared-canvas#49]
https://github.com/soggybag/shared-canvas/blob/e393e3cb319c17a743aa4baab0f4c6bd7c1448ec/tian.js#L9

Good work, but there is room for improvement! You have defined the x and y variables but you didn't use them in the drawing code! If you have to move to a different location you'd have a lot of work to do. Not too mention these numbers don't draw in your location as it is! 

Consider this: 

```js
ctx.arc(x + size / 2, y + size / 2, 50, 0, Math.PI * 2, true); // draw in the center of your location

ctx.arc(x + size / 2, y + 80, 25, 0, Math.PI, false); // draws in the center 80 px from the top
```

**Comment by tian142** [comment]
Fixed* Thank you!

**Comment by soggybag** [comment]
Looks good!
